---
- name: Provision LEMP and related tools
  hosts: all
  become : true
  gather_facts: yes

  roles:
     - update
     - common
   #  - nginx
     - php
  #  - mysql
     - initapps
  #   - restartsvcs
