---
- name: Provision LEMP and related tools
  hosts: web
  become : true
  gather_facts: yes

  roles:
  #   - update
  #   - common
  #   - nginx
  #   - php
     - mysql
  #   - initapps
  #   - restartsvcs
